/* This file was generated by the CARBONSTEEL compiler */
#include <stdint.h>
#include <stdbool.h>
/* Prefix end */

#include <string.h>

typedef struct alpha_t {
	int32_t* a;
} alpha_t;

typedef struct beta_t {
	int16_t a;
	alpha_t b;
} beta_t;

typedef alpha_t gamma_t;

alpha_t function(beta_t* arg) {
	int32_t number = 7;
	alpha_t _cst_tmpvar_0_;
	_cst_tmpvar_0_.a = &number;
	beta_t _cst_tmpvar_1_;
	_cst_tmpvar_1_.a = (*arg).a;
	_cst_tmpvar_1_.b = _cst_tmpvar_0_;
	beta_t var = _cst_tmpvar_1_;
	if (var.a == 7) {
		while (var.a > 0) {
			var.a--;
		}
	}
	beta_t _cst_tmpvar_2_;
	_cst_tmpvar_2_.a = (*arg).a;
	_cst_tmpvar_2_.b = (*arg).b;
	return _cst_tmpvar_2_.b;
}

